-- Auto-generated by Main.hs
-- For input church-zero
-- This code works only for Church Encoding expressions
-- It will compute the ...
-- ... generated CPS translated expression Church enconding

-----------------------------------------------------------

cbn k = let v0(f, k0) = let v1(x, k1) = x(k1) in k0(v1) in k(v0)

cbv k = let v0(f, k0) = let v1(x, k1) = k1(x) in k0(v1) in k(v0)

-----------------------------------------------------------

inc_cbv :: (Int, Int -> r) -> r
inc_cbv (n, k) = k (1 + n)

test_cbv = 
    cbv (\f -> f (inc_cbv, \x -> x (0, id)))

thunk :: a -> (a -> r) -> r
thunk x k = k x

inc_cbn :: (Int -> r, Int) -> r
inc_cbn (k, n) =
    inc_cbv (n, k)

test_cbn =
    cbn (\f -> f (thunk inc_cbn, \x -> x (id, 0)))

main :: IO ()
main = do
  print $ (test_cbn, test_cbv)
